board/models.py
from app import db

# db.Model을 상속받은 테이블을 만듭니다.
class Question(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    subject = db.Column(db.String(200), nullable=False)
    content = db.Column(db.Text(), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), nullable=False)
    # user테이블 pk로 작성자를 구분 - nullable=False 로 변경, ondelete='CASCADE'로 변경 
    # user_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), nullable=False)
    user = db.relationship('User', backref=db.backref('question_set'))

class Answer(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    question_id = db.Column(db.Integer, db.ForeignKey('question.id', ondelete='CASCADE'))
    question = db.relationship('Question', backref=db.backref('answer_set')) # question을 통해 answer_set 
    content = db.Column(db.Text(), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)
    # 작성자를 넣을것
    # user_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), nullable=True, server_default="1")
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), nullable=False)
    user = db.relationship('User', backref=db.backref('answer_set'))  # user를 통해 answer_set 

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(8), nullable=False, unique=True)
    # password = db.Column(db.String(25), nullable=False)
    # mysql에서 hash 알고리즘 적용한 비밀번호 들어가도록 DB Upgrade
    password = db.Column(db.String(300), nullable=False)
    email = db.Column(db.String(100), unique=True, nullable=False)
    

board/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, PasswordField, EmailField
from wtforms.validators import DataRequired, Length, EqualTo, Email

class QuestionForm(FlaskForm):
    subject = StringField('제목', validators=[DataRequired("10글자 넘는 글자를 입력하세요!!"),  Length(max=10)])
    content = TextAreaField('내용', validators=[DataRequired("내용을 꼭 입력하셔야 합니다!!!")])


class AnswerForm(FlaskForm):
    content = TextAreaField('내용', validators=[DataRequired()])


class UserCreateForm(FlaskForm):
    username = StringField('사용자이름', validators=[DataRequired(), Length(min=3, max=8)])
    password1 = PasswordField('비밀번호', validators=[
        DataRequired(), EqualTo('password2', '비밀번호가 일치하지 않습니다')])
    password2 = PasswordField('비밀번호확인', validators=[DataRequired()])
    email = EmailField('이메일', validators=[DataRequired(), Email()])


class UserLoginForm(FlaskForm):
    username = StringField('사용자ID', validators=[DataRequired(), Length(min=2, max=8)])
    password = PasswordField('비밀번호', validators=[DataRequired()])

board/__init__.py
# __init__ 이라는 파일명을 읽어서 app의 조각이구나 인식함.

board/views/answer_views.py
# Blueprint 기능을 사용
from flask import Blueprint, render_template, redirect, url_for, request, flash, g
from ..models import Question, Answer
from ..forms import QuestionForm, AnswerForm
from app import db
from datetime import datetime
from board.views.auth_views import login_required


abp = Blueprint('answer', __name__, url_prefix='/answer')

# 댓글 조회

# 댓글 작성
# 1. GET - 작성 버튼을 누르면 작성 form으로 이동 
# 2. POST - 완료 버튼을 누르면 DB에 답변을 저장하고, 저장된 글을 확인케 위해 특정 글번호로 이동을합니다.
# @abp.route('/create/<int:question_id>', methods=('GET', 'POST'))
# # @login_required # 실습 - answer_views에도 적용
# def create(question_id):
#     form = AnswerForm()
#     question = Question.query.get(question_id)
#     if form.validate_on_submit(): # csrf_token + 로그인기능
#         # db에 저장
#         answer = Answer(question_id=2, content=form.content.data, create_date=datetime.now())
#         db.session.add(answer)
#         db.session.commit()
#         # 2번글의 detail로 이동
#         return redirect(url_for('board.detail', question_id=question_id))
#     return render_template('board/boardDetail.html', question=question, form=form)


@abp.route("/create/<int:question_id>", methods=["POST"])
def create(question_id):
    # AnswerForm으로 화면에서 받은 데이터를
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    # 우리가 요청한 조건에 맞으면
    if form.validate_on_submit():
        a = Answer(question_id=question_id, \
                   content=form.content.data, \
                    create_date=datetime.now(),
                    user=g.user)
        # DB에 저장
        # question.answer_set.append(a)
        db.session.add(a)   
        db.session.commit()  
        # board_views.py의 detail 함수를 호출하는데 question_id를 함께 전달
        return redirect(url_for('board.detail', question_id=question_id))
    # 빈 화면으로 넘기기
    return render_template('question/boardDetail.html', question=question, form=form)

@abp.route("/modify/<int:answer_id>", methods=('GET', 'POST'))
@login_required
def modify(answer_id):
    # 답변을 가져온다
    answer = Answer.query.get_or_404(answer_id)
    question_id = answer.question_id
    # 지금 답변을 변경하려는 사람(로그인한사람)이 작성자인지 확인한다
    if g.user != answer.user: 
        flash('수정권한이 없습니다')
        return redirect(url_for('board.detail', question_id=question_id))
    # 아니면 flash로 에러메시지 전달
    # 맞으면, post로 값이 왔으면
    if request.method == 'POST':
        form =AnswerForm()
        if form.validate_on_submit():
            form.populate_obj(answer) # 화면에 원래 db에서 꺼낸 값을 변경해서 뿌림
            db.session.commit()
            return redirect(url_for('board.detail', question_id=question_id))
            # 값을 수정하여 다시 session에 commit
    else: # GET으로 요청이 왔을 때
        form = AnswerForm(obj=answer)
    # modify라는 변수 사용하여 있으면 answer.modify로 동작하도록 변경
    return render_template('answer/answerForm.html', form=form, answer_id=answer_id, modify=True)
    # 원래 화면으로 redirect


@abp.route("/delete/<int:answer_id>")
@login_required
def delete(answer_id):
    # 글을 가져옴
    answer = Answer.query.get_or_404(answer_id)
    # 현재 접속한 사용자와 글의 작성자가 일치하는지 확인
    question_id= answer.question_id
    if g.user != answer.user: 
        flash('댓글 삭제 권한이 없습니다')
    #     일치하지 않으면 -> 삭제권한이 없습니다 메시지 출력
        return redirect(url_for('board.detail', question_id=question_id))
    #     원래 글로 되돌아감
    db.session.delete(answer)
    db.session.commit()
    return redirect(url_for('board.detail', question_id=question_id))

board/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect
import functools

from app import db
from board.forms import UserCreateForm,  UserLoginForm
from board.models import User

auth = Blueprint('auth', __name__, url_prefix='/auth')


@auth.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data,
                        password=generate_password_hash(form.password1.data), email=form.email.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')
    return render_template('auth/signup.html', form=form)



# /login/ URL과 매핑되는 login 함수는 signup 함수와 비슷하게 동작합니다. POST 방식에는 로그인을 수행하고, GET 요청에는 로그인 화면을 보여줍니다.
@auth.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
				# 폼 입력으로 받은 username으로 데이터베이스에 해당 사용자가 있는지를 검사하고, 만약 사용자가 없으면 "존재하지 않는 사용자입니다."라는 오류를 발생시키고, 사용자가 있다면 폼 입력으로 받은 password와 check_password_hash 함수를 사용하여 데이터베이스의 비밀번호와 일치하는지를 비교합니다.
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            # 사용자도 존재하고 비밀번호도 일치한다면 플라스크 세션(session)에 사용자 정보를 저장합니다.

						# 세션에 user_id라는 객체 생성
            session.clear()
            session['user_id'] = user.id
            _next = request.args.get('next', '')
            if _next:
                return redirect(_next)
            else:
                return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html', form=form)


@auth.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)


@auth.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is None:
            _next = request.url if request.method == 'GET' else ''
            return redirect(url_for('auth.login', next=_next))
        return view(*args, **kwargs)
    return wrapped_view

board/views/board_views.py
# Blueprint 기능을 사용
from flask import Blueprint, render_template, redirect, url_for, request, g, flash
from ..models import Question, Answer
from ..forms import QuestionForm, AnswerForm
from app import db
from datetime import datetime
from board.views.auth_views import login_required


cbp = Blueprint('board', __name__, url_prefix='/board')


# templates 디렉토리 안에 들어있는 file 경로를 읽고, view에 작성한 객체를 달아서 렌더링해서 전달
# 전체 게시글을 db에서 조회해서 가져와서 리스트
# @cbp.route('/list')
# def list():
#     question = Question.query.all()
#     return render_template('board/boardList.html', question_list=question)


@cbp.route('/list')
def list():
    page = request.args.get('page', type=int, default=1)  # 페이지
    question_list = Question.query.order_by(Question.create_date.desc())
    question_list = question_list.paginate(page=page, per_page=10)
    return render_template('board/boardList.html', question_list=question_list)

# 개별 게시글을 조회할 수 있는 함수
@cbp.route('/details/<int:question_id>/')
def detail(question_id):
    # get_or_404() 메서드로 값을 조회하면 404에러를 발생시킵니다.
    # question = Question.query.get(question_id)
    question = Question.query.get_or_404(question_id)
    form = AnswerForm()
    return render_template('board/boardDetail.html', question=question, form=form, question_id=question_id)

# 개별 게시글을 작성
# 1. 작성 버튼을 누르면 게시글 작성하기 위한 form으로 이동 
# 2. 완료 버튼을 누르면 DB에 글을 저장하고, 저장된 글을 확인케 위해 전체 list로 이동을합니다.
# @cbp.route('/create/', methods=('GET', 'POST'))
# # @login_required # 실습 - answer_views에도 적용
# def create():
#     form = QuestionForm()
#     if request.method == 'POST' and form.validate_on_submit():
#         question = Question(subject=form.subject.data, content=form.content.data, create_date=datetime.now())
#         db.session.add(question)
#         db.session.commit()
#         return redirect(url_for('board.list'))
#     return render_template('board/questionForm.html', form=form)


@cbp.route('/create/', methods=['GET', 'POST'])
@login_required # 접근 권한을 확인하기 위한 데코러이터 
def create():
    # 폼을 받는다
    form = QuestionForm()

    # 폼에 온 양식이 우리가 forms.py에 작성한 양식과 일치하는지 확인한다
    if form.validate_on_submit():
    # 일치하면 성공을 의미하는 주소로 전달한다

       q = Question(subject=form.subject.data, \
                   content=form.content.data, \
                    create_date=datetime.now(),
                    user_id=g.user.id)                                                 
       db.session.add(q)
       db.session.commit()
       return redirect( url_for( 'board.list' ) )    
    return render_template('board/questionForm.html', form=form)


@cbp.route("/modify/<int:question_id>", methods=('GET', 'POST'))
@login_required
def modify(question_id):
    # 글을 가져온다
    question = Question.query.get_or_404(question_id)
    # 지금 글을 변경하려는 사람(로그인한사람)이 작성자인지 확인한다
    if g.user != question.user: 
        # 아니면 flash로 에러메시지 전달
        flash('수정권한이 없습니다')
        return redirect(url_for('board.detail', question_id=question_id))
    # 지금 글을 변경하려는 사람이 작성자이고, post로 값이 왔으면
    if request.method == 'POST':
        form = QuestionForm()
        if form.validate_on_submit():
            form.populate_obj(question) # 화면에 원래 db에서 꺼낸 값을 변경해서 뿌림
            db.session.commit()
            return redirect(url_for('board.detail', question_id=question_id))
            # 값을 수정하여 다시 session에 commit
    else: # GET으로 요청이 왔을 때
        # 원래 화면으로 redirect
        # 수정화면으로 다시 form과 함께 돌려보낸다
        form = QuestionForm(obj=question)
    return render_template('board/questionForm.html', form=form)


@cbp.route("/delete/<int:question_id>")
@login_required
def delete(question_id):
    # 글을 가져옴
    question = Question.query.get_or_404(question_id)
    # 현재 접속한 사용자와 글의 작성자가 일치하는지 확인
    if g.user != question.user: 
        flash('삭제권한이 없습니다')
    #     일치하지 않으면 -> 삭제권한이 없습니다 메시지 출력
        return redirect(url_for('board.detail', question_id=question_id))
    #     원래 글로 되돌아감
    db.session.delete(question)
    db.session.commit()
    # 게시글 목록으로 되돌아감 
    return redirect(url_for('board.list'))


# Blueprint 기능을 사용해서 collection/no1/
@cbp.route('/no1')
def hello2():
    return f'{__name__} 첫번째'
    
@cbp.route('/no2')
def hello3():
    return f'{__name__} 두번째'
    

board/views/main_views.py
from flask import Blueprint, render_template

import logging

logger = logging.getLogger('my') 

# 특정 /main/ 하위에 있는 함수들을 일괄적으로 관리하기 위한 flask의 기능
                # 코드에서 부르는 상대적 이름, 실제 파일명, url에 매칭되는 경로 
mbp = Blueprint('main', __name__, url_prefix='/')

# localhost:5001/main/

# localhost:5001로 접속하면 index.html을 화면에 렌더링하도록 변경해주세요.
@mbp.route('/')
def index():
    logger.info('INFO 레벨의 메시지 기록 확인')
    logger.warning('WARNING 레벨의 메시지 기록 확인')
    logger.error('ERROR 레벨의 메시지 기록 확인')
    return render_template('index.html')

# # Flask에서 값을 주소줄로 입력받아서 사용하는 방법
# # <변수명>  /변수명
# @mbp.route('/<username>')
# def print_string(username):
#     return f'{__name__} {username} hello'

# # <자료형:변수명> 
# # <path:변수명> : / 를 포함한 서브경로 전달
# # <float:변수명> : float 전달
# # <int:변수명> : int로 전달
# @mbp.route('/path/<path:subpath>')
# def print_path(subpath):
#     return f'{__name__} {subpath} hello'

# @mbp.route('/상품명/')
# @mbp.route('/items/')
# @mbp.route('/items/<itemname>')
# @mbp.route('/items/<itemname>/<quantity>')
# def print_itemname(itemname='기본값', quantity=0):
#     # print(type(quantity))
#     return f'{__name__} {itemname, quantity} hello'

templates/board/boardDetail.html
{% extends 'base.html' %}

{% block content %}

{% include 'form_errors.html' %}
<div class="container my-3">
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ question.user.username }}
                </div>
                <div class="badge bg-light text-dark p-2">
                    {{ question.create_date | date_time }}
                </div>
            </div>
            <!-- 로그인 된 상태 (g.user), 작성자가 로그인한 사용자와 일치하는 상태-->
            {% if g.user == question.user %}
            <a class="btn btn-primary" href="{{ url_for('board.modify', question_id=question.id ) }}">수정</a>
            <a class="btn btn-primary" href="{{ url_for('board.delete', question_id=question.id ) }}">삭제</a>
            {% endif %}
        </div>
    </div>
       
    {% include 'answer/answerForm.html' %}
    
    <h5 class="border-bottom my-3 py-2">{{ question.answer_set|length }}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ answer.user.username }}
                </div>
                <div class="badge bg-light text-dark p-2">
                    {{ answer.create_date }}
                </div>
                            <!-- 로그인 된 상태 (g.user), 작성자가 로그인한 사용자와 일치하는 상태-->
                {% if g.user == answer.user %}&nbsp;&nbsp;
                <a class="btn btn-primary" href="{{ url_for('answer.modify', answer_id=answer.id ) }}">수정</a>&nbsp;&nbsp;
                <a class="btn btn-primary" href="{{ url_for('answer.delete', answer_id=answer.id ) }}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <br>
    <br>

    

{% endblock %}

templates/board/boardList.html
{% extends 'base.html' %}
{% block content %}
 
<!-- 질문 목록 -->
{#  render_template 함수에서 전달받은 질문 목록 데이터 question_list가 있는지 검사 #}
{% include 'form_errors.html' %}

<div class="container my-3">
  {% if g.user %}
    <a href="{{ url_for('board.create') }}" class="btn btn-primary float-end">질문 등록</a>
    {% endif %}
    <br>
    <br>
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        
        <tr>
            <td>{{ question_list.total - ((question_list.page-1) * question_list.per_page) - loop.index0 }}</td>
            <td>
                <a href="{{ url_for('board.detail', question_id=question.id) }}">{{ question.subject }}</a>
            </td>
            <td>{{ question.create_date | date_time2 }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    <!-- 페이지네이션 시작 -->
    <nav aria-label="...">
        <ul class="pagination justify-content-center">
          {% if question_list.has_prev %}
          <li class="page-item">
            <a class="page-link" href="?page={{ question_list.prev_num }}">이전</a>
          </li>
          {% else %}
          <li class="page-item disabled">
            <a class="page-link">이전</a>
          </li>
          {% endif %}
          <!-- 페이지 번호 반복 출력 -->
           {% for num in question_list.iter_pages() %}
            {% if num %}
            <!-- num이 question_list.page와 같으면  -->
                {% if num == question_list.page %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                  </li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                {% endif %}
            {% endif %}
          {% endfor %}

    
          
          {% if question_list.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_num }}">다음</a>
          {% else %}
          <li class="page-item disabled">
            <a class="page-link">다음</a>
          </li>
          {% endif %}

        </ul>
      </nav>
    <!-- 페이지네이션 끝 -->
     
      <br><br><br><br><br>
</div>

{% endblock %}

templates/board/questionForm.html
{% extends 'base.html' %}
{% block content %}
<!-- 질문 등록 -->
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문 올리기</h5>
    <form method="post" class="my-3">
        {% include "form_errors.html" %}
        {{ form.csrf_token }}

		{# Form에서 작성한 라벨 #}
        {{ form.subject.label }}

		{# Form에서 작성한 필드. 값을 입력 받아야 하는 '폼'이므로 호출연산자로 작성 #}
        {{ form.subject(class="form-control") }}

        {{ form.content.label }}
        {{ form.content(class="form-control") }}

        <button type="submit" class="btn btn-primary">저장</button>
    </form>
</div>
{% endblock %}